INSTALL( TARGETS ${PROJECT_NAME}
         EXPORT  LipiTkLibraryDepends
         RUNTIME DESTINATION ${CMAKE_INSTALL_PREFIX}/bin
         LIBRARY DESTINATION ${CMAKE_INSTALL_PREFIX}/lib
         ARCHIVE DESTINATION ${CMAKE_INSTALL_PREFIX}/lib/static 
)


# set_target_properties(foo PROPERTIES
#   PUBLIC_HEADER "foo.h;${CMAKE_CURRENT_BINARY_DIR}/config.h")

# install(TARGETS ${PROJECT_NAME}
#   # IMPORTANT: Add the foo library to the "export-set"
#   EXPORT ${PROJECT_NAME}LibraryDepends
#   RUNTIME DESTINATION "${INSTALL_BIN_DIR}" COMPONENT bin
#   LIBRARY DESTINATION "${INSTALL_LIB_DIR}" COMPONENT shlib
#   PUBLIC_HEADER DESTINATION "${INSTALL_INCLUDE_DIR}/foo"
#     COMPONENT dev)
